http-rs/async-h1

- README.md
- src/lib.rs
The code of this crate is 100% safe Rust, but the lint setting in the README is not accurate.
> Actually forbid unsafe code

- src/chunked.rs
- src/client.rs
- src/server.rs
- tests/fixtures/request-unexpected-eof.txt
- tests/fixtures/response-unexpected-eof.txt
- tests/server.rs
Fixes #67. Also fixes some state machine bugs found during testing. This might fix #63 also, I haven't tested it though.
This PR moves internal state to the end if the body ends unexpectedly.
> Fix stream freezing when body ends unexpectedly

- src/chunked.rs
- tests/fixtures/request-invalid-trailer.txt
- tests/server.rs
Found during fuzz testing. This fixes a panic by propagating `Result` value. Thanks!
> Fix panic with invalid trailer

- rustfmt.toml
We use `rustfmt` in this project to format code.  However, if someone
were to have his or her own local rustfmt configuration, that person's
configuration would be in effect when running rustfmt on this project,
potentially leading to inconsistent formatting.
Let's add a `rustfmt.toml` file.  That way, our own configuration will
always be used, as per-project configuration overrides any per-user
configuration.
With the configuration we're adding in this commit, rustfmt does not
make any changes when run.
> Add rustfmt configuration

- src/lib.rs
- src/server/mod.rs
`MAX_REQUESTS` is introducing errors when they are not actually needed in the current configuration. If a user needs to limit incoming connections, this should happen more intelligently at a higher level in the stack.
Note: neither hyper nor nodejs have this builtin asfaict
> feat(server): configurable timeout + drop max_reqs

- LICENSE-APACHE
- LICENSE-MIT
In commit f7270411efdd0011359deac82a2e224629e7f671, we copied our date
implementation from the `httpdate` project [1] (#6, #19).  However,
this was done without proper attribution and preservation of copyright
notices.  Let's fix this.
[1] https://github.com/pyfisch/httpdate
> Fix attribution of `date.rs`

- src/client/decode.rs
- tests/client.rs
- tests/fixtures/response-newlines.txt
While the HTTP standard specifies that the status-line and header-fields
should be terminated with a CRLF (\r\n), many implementations on the
internet would wrongly output only LF (\n). This is even recognized in the
RFC which  suggests that a LF may be recognized as a line terminator.
https://tools.ietf.org/html/rfc7230#section-3.5
>   Although the line terminator for the start-line and header fields is
>   the sequence CRLF, a recipient MAY recognize a single LF as a line
>   terminator and ignore any preceding CR.
This commit introduces a test for a response with only LF newlines.
> add test for response with newlines instead of \r\n

- Cargo.toml
- src/client/encode.rs
the request can already contain a host header, either because it came
from the async_h1::accept, or because the user set it manually. In that
case don't add a second host header (the one based on `req.url()`).
> Don't add the Host header if it already exists

- src/client/encode.rs
- tests/fixtures/request-add-date.txt
- tests/fixtures/request-with-connect.txt
The date header is optional for clients, but also seems to be
discouraged. It's so rare so maybe leave it to the user.
https://tools.ietf.org/html/rfc7231#section-7.1.1.2
> A user agent MAY send a Date…
The older RFC https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.18
> Clients SHOULD only send a Date header field in messages that include an entity-body, as in the case of the PUT and POST requests, and even then it is optional. A client without a clock MUST NOT send a Date header field in a request.
> no need to send date header in client

- src/server/encode.rs
the response can already contain a date header, either because it came
from the async_h1::client::connect, or because the user set it manually.
In that case don't add a second date header.
> Don't add the Date header in a response if it already exists

- src/server/encode.rs
the Response (res) in server::encode::Encoder might already have
content-length or transfer-encoding, which even might be wrong (if set
manually). Filter them out when iterating the response headers, proper
values were anyway written to the head before.
> filter out content-length and transfer-encoding from pass Response

- examples/server.rs
- src/lib.rs
- src/server/decode.rs
- src/server/mod.rs
- tests/fixtures/request-unexpected-eof.txt
- tests/fixtures/request-with-host.txt
- tests/fixtures/response-with-host.txt
- tests/server-chunked-encode-large.rs
- tests/server-chunked-encode-small.rs
- tests/server.rs
because the host header is mandatory for http/1.1, the addr argument to accept is unnecessary and unused. this builds upon #106
> No addr needed for accept

- src/server/decode.rs
- tests/fixtures/request-with-host.txt
- tests/fixtures/response-with-host.txt
- tests/server.rs
With this change, the request.url() represents what the client is actually requesting.
Scenario: An async-h1-based server is bound to `127.0.0.1:3000` and proxied through a load balancer that's externally visible at `https://vhost.example.com`. Prior to this commit, a request to `/index.html` would have a request.url() of `http://127.0.0.1:3000/index.html`. After this change, the `request.url()` would be `http://vhost.example.com/index.html`.
It is awkward that we have to parse a url and then substitute the host information, but this due to the fact that Request::new takes a url, and header parsing currently requires a constructed request. To address this, the Request constructor should not require a Url, but that can be done as a later refactor.
This PR does not set the scheme from proxy …
> set request url host from host header

- src/chunked/encoder.rs
- src/server/encode.rs
- src/server/mod.rs
This reworks the server encoder to similar to the chunked encoder. The main benefit of this is that we now use an internal state machine which logs each state transition and how many bytes have been written, making it possible to debug using `log` instead of having to manually insert debug statements.
Also gave some variables and functions the same name so that the two encoders are comparable. And documented what each state does. Thanks!
__edit:__ this was done in response to seeing a report in https://github.com/http-rs/tide/issues/458 -- I wish we could ask the user there to log out the full intermediate parsing steps so that we can look whether we can spot anything strange from the outset.
> Server encoder state machine

- Cargo.toml
- src/server/decode.rs
- tests/client.rs
closes #115, which was identified by #114 
This also removes the previous awkward step of parsing a Url and then later replacing the host — Url extraction from a httparse::Request is done all in one place for locality of reference.
Please suggest any additional test cases that aren't covered by the unit tests. Thanks!
> more robust Url extraction directly from the httparse::Request

- src/server/decode.rs
A 100 Continue response is an HTTP message in its own right, and must therefore be correctly delineated from the actual response by \r\n\r\n. curl will fail with the current code, as it cannot decode the two HTTP messages correctly.
> Fix 100 Continue

- src/server/encode.rs
- src/server/mod.rs
- tests/fixtures/head_request.txt
- tests/fixtures/head_response.txt
- tests/server.rs
Refs http-rs/tide#623, closes #125 
HTTP HEAD responses [MUST NOT](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.4) include response body content, but async-h1 does not currently support the ability to omit the response body and still send a content-length header.
Attempts to close this at the http-types layer left async-h1 hanging indefinitely because async-h1 uses the same notion of body length for the header and the actual response body sending. In order to address this at the async-h1 level, the encoder needs to know the request method.  No public API as of this commit is changed by this spec-conformance bugfix.
> do not send body content in reply to HEAD requests

- src/client/encode.rs
- tests/client.rs
- tests/fixtures/request-with-fragment.txt
The fragment part of an URL is purely for the client and is not expected to be sent to the client.
Referring [RFC7230](https://tools.ietf.org/html/rfc7230#section-5.1), and [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.5). Excerpt below:
> 5.1.  Identifying a Target Resource
> [...] The target URI excludes the reference's fragment component, if any,
> since fragment identifiers are reserved for client-side processing
> ([RFC3986], Section 3.5).
> 3.5.  Fragment
> [...] As such, the fragment identifier is not used in the
> scheme-specific processing of a URI; instead, the fragment identifier is
> separated from the rest of the URI prior to a dereference, and thus the
> identifying information within the fragment itself is dereferenced solely
> by the user agent, regardless of the …
> Client must not send fragment of URL

- Cargo.toml
- src/lib.rs
- src/read_notifier.rs
- src/server/decode.rs
- tests/continue.rs
closes #135. if a client says it expects 100-continue and we never read the body, we never send 100 continue and the client will have the option not to send a body.
this is implemented using a `ReadNotifier` which forwards BufRead and Read and sends a message on an async channel on first read. a task is spawned for each request which awaits that message and sends 100-continue.
the approach to testing might have been overkill for this pr, but hopefully sets us up to do other complex testing with async-h1
> don't send 100-continue until the body has been read from

- src/chunked/decoder.rs
- src/lib.rs
closes #142 
async_std::io::copy needs to be able to read 0 several times while it waits for the writer to flush. Previously, we returned 0 once and then waited for further input, instead of returning 0 repeatedly once end-of-file has been hit. Maybe copy shouldn't be polling after eof, but that is a distinct concern.
> Allow chunked decoder to read-poll after eof

- src/server/decode.rs
Fixes #148 
When a request is decoded and contains multiple headers, in case there are multiple header values for the same header name, the current code will result in only the last header value being added to the map.
This PR uses `append_header` to ensure that if there are multiple header values to the same name, they're appended to the headers map.
> For each header from an incoming request, use append instead of insert

- Cargo.toml
I added it to cargo.toml before I realized that it was only needed for tests
> move async-channel to dev deps

- src/server/decode.rs
cc http-rs/tide#733
Before, pathnames that start with two slashes, like `//foo` and `//`, are parsed
incorrectly as protocol-relative ones. This PR fixes this.
> Handle paths that starts with double slashes

- tests/common/mod.rs
- tests/server.rs
side note: async-dup is incredibly useful and maybe async-std should consider integrating it somehow, like maybe `async_std::io::{Arc, Mutex}`?
This is the clippy that this PR fixes, currently failing on main:
> address clippy concern about holding a sync mutex lock across an await boundary

- src/server/decode.rs
- tests/test_utils.rs
This sets the 400 status code when using chunked encoding + content-length rather than the 500 status we had before. It also updates our `Content-Length` parser on the server to use the typed implementation which ensures the last defined value is always used, which is according to spec. Thanks heaps!
> 400 on content len chunked

- examples/server.rs
- src/lib.rs
- src/server/mod.rs
- tests/accept.rs
- tests/test_utils.rs
Async-h1 is a low-level library for use by other crates, and error handling within endpoint functions should be handled by higher levels of abstraction. From a http library's perspective, all requests must have a response.
> change: async-h1 endpoints always return a response

- src/server/decode.rs
- src/server/mod.rs
- tests/continue.rs
- tests/server-chunked-encode-large.rs
- tests/server_decode.rs
this pr adds support for http/1.0, enabled by the `accept_with_opts` api caller providing a default host in ServerOptions. http frameworks like tide could surface this as a configuration option to the end user
There may be further work that needs to be done in order to completely support 1.0, but this addresses the biggest blocker and enables us to explore which of the other differences need to be handled at the async-h1 layer
Useful Reference: http://www.ra.ethz.ch/cdstore/www8/data/2136/pdf/pd1.pdf
closes #152
closes #122
> Optional http/1.0 support

- src/server/mod.rs
firefox send websocket upgrade header "Connection:keep-alive, Upgrade" can't match with connection_header_as_str.eq_ignore_ascii_case("upgrade")
> fix firefox can't entablish websocket.

- Cargo.toml
With the next http-types release, this will allow omitting the cookie
feature and associated dependencies.
> Disable default-features on http-types

- Cargo.toml
- src/client/decode.rs
- src/client/mod.rs
- src/error.rs
- src/lib.rs
- src/server/decode.rs
- src/server/mod.rs
- tests/client_decode.rs
- tests/server-chunked-encode-large.rs
- tests/server_decode.rs
- tests/test_utils.rs
using a dynamic error like anyhow is ideally suited to application code, not library code. async-h1 can enumerate every type of error that can occur, and it should do so.
we may want to revise the details of error enum before 3.0, but this represents a first effort at removing http_types::Error from async-h1.
> Use concrete errors

- tests/test_utils.rs
> Fix race condition in test-utils CloseableCursor implementation

- Cargo.toml
- src/chunked/decoder.rs
- src/server/decode.rs
- src/server/mod.rs
- tests/client_decode.rs
This simplifies and shortens the implementation, and fixes the bug in the process.
This now parses offsets byte-at-a-time.
> Rewrite `Transfer-Encoding: chunked` support to fix #195

- Cargo.toml
- src/body_encoder.rs
- src/chunked/decoder.rs
- src/chunked/encoder.rs
- src/client/decode.rs
- src/client/encode.rs
- src/client/mod.rs
- src/lib.rs
- src/read_notifier.rs
- src/server/body_reader.rs
- src/server/decode.rs
- src/server/encode.rs
- src/server/mod.rs
It would be nice to be able to use this in environments where I use
smol. However this crate imports the async-std crate for I/O. This
commit partially replaces async-std with the equivalent combinators from
futures-lite and async-io, two smol crates that async-std depends on
anyways.
The task spawn is still left in, as replacing it will be controversial. Thus far I've just replaced it with `async-global-executor`, which is what `async-std` uses anyways. This is a placeholder until we can discuss what the best way of not using a global executor is.
> Replace async-std with smol crates
